### ISSUE TITLE
plugin-encryption: _getAuthorization() should utilize the 'spark:kms' scope

### ISSUE THREAD

**Issue by andrewholsted** [webex/spark-js-sdk#436]
On line 317 [here](https://github.com/ciscospark/spark-js-sdk/blob/8f021ffad3095e491bb2db0d8975ec7f721b3e3c/packages/plugin-encryption/src/kms.js#L317), no scope is passed to `spark.credentials.getAuthorization()` which returns the API token by default. Passing`spark:kms` here correctly downscopes the supertoken to a kms specific token and returns it.

**Comment by mattnorris** [comment]
@andrewholsted I believe this is [fixed](https://github.com/webex/spark-js-sdk/blob/master/packages/node_modules/@ciscospark/internal-plugin-encryption/src/kms.js#L443). Please let me know if you see any issues.
