### ISSUE TITLE
Support file thumbnail downloads

### ISSUE THREAD

**Issue by shenning00** [webex/spark-js-sdk#471]
Support the ability to retrieve a list of transcoded ("thumbnail") images of a document.

CIsco Spark supports the capability of transcoding uploaded documents to images of the pages of the documents. These images should be accessible through the API and associated SDK's.

**Comment by olivierproffit** [comment]
Hi @shenning00 sorry that ticket is very old, is it still needed for you? If yes, do you need thumbnails or full size transcoded document ?

**Comment by mattnorris** [comment]
@shenning00 please reopen if this is still a need for you. Thanks!
