### ISSUE TITLE
Bug: Incorrect SDK version shows up on web-client

### ISSUE THREAD

**Issue by saurjai3** [webex/spark-js-sdk#669]
When I updated the recipe-private-client to 1.6.1 keeping the spark-core as 1.6.0, the sdk version on web-client Ux shows it as 1.6.0. Although I would want it to appear as 1.6.1 instead.
![11_53_27](https://user-images.githubusercontent.com/22205801/28983211-8fecb37e-790d-11e7-9bd0-4900b874a03c.jpg)

**Comment by ianwremmel** [comment]
This can happen when the overall sdk version increases without a change to spark-core. Right now, only spark-core and ciscospark have explicit version numbers, so if spark-core doesn't update even if a plugin does, we don't see the real version number.
