### ISSUE TITLE
Issue with Refresh Tokens

### ISSUE THREAD

**Issue by cseale** [webex/spark-js-sdk#681]
Hi,

I am having issues using refresh tokens with the `spark-core` api. I am trying to create a Spark Instance using my access token and refresh token. However, when attempting to authorise after the access token has expired, the JS-SDK doesn't seem to recognise that a refresh token has been provided and never attempts to refresh the access token.

This functionality was working for me in the `0.6.X` version of the spark-core API. (I have only recently upgraded). Has the API changed?

My code looks like this, modified slightly from the React-Ciscospark repo:

```
export default function createSpark(accessToken, refreshToken) {
  // Check if we already have a spark instance in memory
  let ciscosparkInstance = window.ciscosparkInstance;
  console.log(`attempting to authorise with the following: `, accessToken, refreshToken);
  if (typeof ciscosparkInstance !== `object`) {
    const credentials = JSON.parse(localStorage.getItem(`credentials`) || false);
    ciscosparkInstance = new Spark({
      credentials: {
        authorization: {
          access_token: accessToken || credentials.access_token,
          refresh_token: refreshToken || credentials.refresh_token
        }
      },
      config: {
        appName: `spark-widgets`,
        appVersion: process.env.REACT_CISCOSPARK_VERSION,
        device: {
          ephemeral: true
        },
        logger: {
          level: process.env.NODE_ENV === `production` ? `silent` : `trace`
        },
        conversation: {
          allowedInboundTags: {
            'spark-mention': [`data-object-type`, `data-object-id`, `data-object-url`],
            a: [`href`],
            b: [],
            blockquote: [`class`],
            strong: [],
            i: [],
            em: [],
            pre: [],
            code: [],
            br: [],
            hr: [],
            p: [],
            ul: [],
            ol: [],
            li: [],
            h1: [],
            h2: [],
            h3: []
          },
          allowedOutboundTags: {
            'spark-mention': [`data-object-type`, `data-object-id`, `data-object-url`],
            a: [`href`],
            b: [],
            blockquote: [`class`],
            strong: [],
            i: [],
            em: [],
            pre: [],
            code: [],
            br: [],
            hr: [],
            p: [],
            ul: [],
            ol: [],
            li: [],
            h1: [],
            h2: [],
            h3: []
          }
        },
        storage: {
          unboundedAdapter: new LocalForageStoreAdapter(`ciscospark-widgets`)
        }
      }
    });
    window.ciscosparkInstance = ciscosparkInstance;
  }

  return ciscosparkInstance;
}
```

Could I get any guidance on this? Thanks.

**Comment by ianwremmel** [comment]
Hi @cseale 

First, note that the react-ciscospark code relies on internal apis that won't generally be available for your app. To avoid unexpected breaking changes, you'll want to limit the code you use to [ciscospark](https://www.npmjs.com/package/ciscospark). 

That said, auth changed pretty significantly between 0.6 and 1.0 (it was pretty much broken in 0.6 and getting it working required hacking internal bits of the sdk). 

[the api doc](https://ciscospark.github.io/spark-js-sdk/api/#browser) has probably the most concise explanation of how to do auth in the post-1.x world, but see the [browser guide](https://ciscospark.github.io/spark-js-sdk/guides/browsers/) for a bit more detail.
