### ISSUE TITLE
People Plugin: notFoundIds causing list failures

### ISSUE THREAD

**Issue by good-joe** [webex/spark-js-sdk#838]
## Expected Behavior
The promise returned from people.list eventually resolves regardless of the presence or absence of notFoundIds in the response body. 
## Current Behavior
The returned promise never resolves when notFoundIds are present. The total IDs batched are returned as the union of body.items and body.notFoundIds. Because the people batcher currently ignores the notFoundIds, the batch can never fully resolve.

## Possible Solution (we welcome any logical suggestion)

I think modifying the batcher's handleHTTPSuccess to combine item and notFoundIds lists will fix the issue.
```
  handleHttpSuccess(res) {
    // combine item and notFoundIds lists
    const batchedIds = res.body.items.concat(res.body.notFoundIds.map((oneId) => {
      return {id: oneId};
    }));
    return Promise.all(batchedIds.map((personResponse) =>
      this.handleItemSuccess(personResponse.id, personResponse)));
  },
```
we essentially make a PPI from the only piece of info we have, the id. If this is not sufficient then these IDs can be trapped and treated as errors later on. As we combine both lists we know our batch will complete.
## Steps to Reproduce
1. Discovered during compact calendar implementation
2.
3.
4.

## Environment Details
* SDK Version 1.28.2
* Node/Browser Version node 8.6, Chrome lateset
* NPM Version 5.6

**Comment by bzang** [comment]
@good-joe. Thanks for reporting this! Could you post an example of a .list() call that will produce a list of notFoundIds? I’ve tried a couple of things and the API only seems to give me bad userid errors.

**Comment by mattnorris** [comment]
This has been captured and prioritized. There is a PR for it, though there are some test failures and conflicts to work through.

**Comment by tahanson-cisco** [comment]
@mattnorris - why was this closed as won't fix?  Looks like this is still an issue with the sdk.

**Comment by mattnorris** [comment]
@tahanson-cisco I believe I closed it after discussing its priority with @olivierproffit . I don't quite remember the details but there was a PR for it at one point. 

@olivierproffit should we take another look?

**Comment by olivierproffit** [comment]
@tahanson-cisco could you ping me from the related internal JIRA ticket so that we discuss it

**Comment by olivierproffit** [comment]
@tahanson-cisco it was closed as won't do because the only requester found a workaround
