### ISSUE TITLE
404 not found on cisco spark npm repo

### ISSUE THREAD

**Issue by jloveric** [webex/spark-js-sdk#854]
I'm getting this error when trying to npm install elements of ciscospark 

npm ERR! 404 Not Found: @ciscospark/plugin-people@1.8.0

Also cisco spark itself github is down

https://github.com/ciscospark/spark-js-sdk/tree/master/packages/ciscospark

Has the repository moved?

**Comment by JustinDupree** [comment]
I believe you're missing a subfolder:

https://github.com/ciscospark/spark-js-sdk/tree/master/packages/node_modules/ciscospark

**Comment by jloveric** [comment]
This is the repo referred to by the npm repository

https://www.npmjs.com/package/ciscospark

**Comment by JustinDupree** [comment]
Tried this:

npm install --save ciscospark

and it installed without issue; it installed a different version of the plugin mentioned in your error:

├── @ciscospark/plugin-people@1.29.4 (@ciscospark/common@1.29.4, babel-runtime@6.26.0)

**Comment by jloveric** [comment]
Ha.  I have a bad .npmrc! Thanks!
