### ISSUE TITLE
regex denial of service vulnerability due to transient dependency on "string" package

### ISSUE THREAD

**Issue by peterswimm** [webex/spark-js-sdk#885]
As first reported here:
https://github.com/howdyai/botkit/issues/1345#issue-322711054

Quote: "Due to following dependency tree

```
├─┬ botkit@0.6.14
│ ├─┬ ciscospark@1.31.3
│ │ ├─┬ @ciscospark/plugin-phone@1.31.3
│ │ │ ├─┬ @ciscospark/internal-plugin-locus@1.31.3
│ │ │ │ ├─┬ @ciscospark/internal-plugin-mercury@1.31.3
│ │ │ │ │ ├── string@3.3.3
```
regex denial of service vulnerability has been introduced, more detail can be found here: https://snyk.io/vuln/npm:string:20170907

**Comment by bzang** [comment]
@mattnorris does your patch from a few weeks ago fix this issue?

**Comment by mattnorris** [comment]
Yes, `string` has been removed: https://github.com/webex/spark-js-sdk/pull/895
