### ISSUE TITLE
Resending Audio, video and screen

### ISSUE THREAD

**Issue by johnob2103** [webex/spark-js-sdk#887]
I'm currently using Firefox (60.0.0) and all functionality seems to work fine, you can stop sending audio/video/screen. However, when you attempt to resend media, there's a warning "ocus: expected audio recvonly (locus) to equal sendrecv (local media)" and upon hanging up a "TypeError: _this14.mediaConnection is undefined" error is thrown by the SDK. I've tested the same scenario in Chrome and everything works perfectly fine, minus of course screen sharing which is a must for my application

**Comment by mattnorris** [comment]
Tracking recent calling bugs in #921
