### ISSUE TITLE
Example code not working -> Bad Request Error

### ISSUE THREAD

**Issue by julianfrank** [webex/spark-js-sdk#890]
## Expected Behavior
Browser Registration supposed to happen as per Example... but not working

## Current Behavior
I get this error message in browser console:
```
GET https://mercury-connection-a.wbx2.com/v1/apps/wx2/registrations/112f2ca5-94a8-43a8-8e2f-35caf1b3b79d/messages?outboundWireFormat=text&bufferStates=true&aliasHttpStatus=true 400 (Bad Request)
```

Even in your demo website https://js.samples.s4d.io/browser-single-party-call/ I get a different error!
```
Uncaught (in promise) Error: Unable to infer service for this url wss://mercury-connection-a.wbx2.com/v1/apps/wx2/registrations/6012375c-1d61-43b6-9b6c-834f89b89487/messages?outboundWireFormat=text&bufferStates=true&aliasHttpStatus=true
    at child.inferServiceFromUrl (service-collection.js:63)
    at device.js:161
    at new Promise (<anonymous>)
    at new F (_export.js:35)
    at child.fetchNewUrls (device.js:161)
    at mercury.js:185
```
## Possible Solution (we welcome any logical suggestion)
No Idea

## Steps to Reproduce

1.Ran App as per https://developer.webex.com/sdk-for-browsers.html#gettingStarted
2.caddy
3.open website on chrome browser => http://localhost:2015
4.Provide Access Token and click "Connect" and this error comes up in console... Nothing happens in ui

## Environment Details

* SDK Version : 1.31.3
* Node/Browser Version : Version 66.0.3359.181 (Official Build) (64-bit)
* NPM Version:5.6.0

**Comment by bzang** [comment]
@julianfrank we are aware of the warning, but this should not affect anything else. Which getting started sample did you run?

**Comment by julianfrank** [comment]
https://developer.webex.com/sdk-for-browsers.html#gettingStarted ... Did the whole stuff as per this page.

**Comment by Colby-6sco** [comment]
@julianfrank  Can you please use the latest SDK or the Demo and confirm if you're still experiencing the issue?

**Comment by jeffmars** [comment]
@julianfrank, there have been several updates to the Browser SDK since this was originally reported. Could you please check to see if you're seeing the issue with the latest version?

**Comment by julianfrank** [comment]
It Works! Thanks
