### ISSUE TITLE
audio/video & camera state / mic state mixed up?

### ISSUE THREAD

**Issue by DJF3** [webex/spark-js-sdk#904]
## Expected Behavior
When you enable/disable video, the camera state goes to ON or OFF
When you enable/disable audio, the microphone state goes to ON or OFF

## Current Behavior
When I click "Stop sending AUDIO", the _Camera state_ switches to OFF
When I click "Start sending VIDEO", the _Microphone state_ switches to ON

So it looks like the state of audio/video is mixed up.

## Environment Details
* Platform: Mac (latest)
* SDK Version: just installed
* Node/Browser Version: Node 3.10.8, browser: Chrome (67)
* NPM Version: 3.10.8

**Comment by mattnorris** [comment]
Tracking recent calling bugs at #921
