### ISSUE TITLE
can't run samples for browser SDK. webpack-cli issue

### ISSUE THREAD

**Issue by chrilian** [webex/spark-js-sdk#961]
## Expected Behavior

Be able to run samples for browser SDK.

## Current Behavior

cannot run samples. Receive this error: 
********
The CLI moved into a separate package: webpack-cli.
Please install 'webpack-cli' in addition to webpack itself to use the CLI.
-> When using npm: npm install webpack-cli -D
-> When using yarn: yarn add webpack-cli -D
internal/modules/cjs/loader.js:583
    throw err;
*******
after install webpack-cli via: npm install webpack-cli -D
and run, I still get the SAME error

## Possible Solution (we welcome any logical suggestion)

Example:  
``
possibly change the node package manager to include a working version if webpack-cli
```
## Steps to Reproduce
<!--- Please provide detailed steps for reproducing the issue -->
1. follow instructions for running samples: 
    git clone git@github.com:webex/spark-js-sdk.git 
    cd spark-js-sdk
    npm install
    npm run samples:serv
(I used: git clone https://github.com/webex/spark-js-sdk.git) instead because I was getting permission issue with the clone in the instructions

## Environment Details
<!--- Provide as much detail as possible about your environment -->
* SDK Version
* Node/Browser Version: Most up-to-date node. issue unrelated to browser
* NPM Version: most up-to-date

**Comment by adamweeks** [comment]
@chrilian what version of node are you using? I am not able to reproduce this issue on v8.11.3
